--- # Ansible Playbook to automate application deployment to Raspberry Pis in a consistent and repeatable way
- hosts: raspberry
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    angular_dist_dir: "{{ lookup('env', 'PWD') }}/dist/windfire-restaurants-ui"
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
    - "{{ src_dir }}/conf/apache2.yml"
  tasks:
    - name: Transfer Angular Files
      copy:
        src: "{{ angular_dist_dir }}"
        dest: "{{ remote_app_home_dir }}"
    - name: Clean Apache2 folder {{ apache2_doc_dir }}
      file:
        path: "{{ apache2_doc_dir }}/"
        state: absent
    - name: Copy Angular application files from {{ remote_app_home_dir }}/{{ remote_app_files_dir }} to Apache2 folder {{ apache2_doc_dir }}
      shell: 'cp -r {{ remote_app_home_dir }}/{{ remote_app_files_dir }} {{ apache2_doc_dir }}'
    - name: Clean folder {{ remote_app_home_dir }}/{{ remote_app_files_dir }}
      file:
        path: "{{ remote_app_home_dir }}/{{ remote_app_files_dir }}/"
        state: absent