apiVersion: v1
kind: Template
metadata:
  name: windfire-restaurants-ui
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: windfire-restaurants-ui
    name: windfire-restaurants-ui
  spec:
    replicas: 1
    selector:
      app: windfire-restaurants-ui
      deploymentconfig: windfire-restaurants-ui
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: windfire-restaurants-ui
          deploymentconfig: windfire-restaurants-ui
      spec:
        containers:
        - image: docker.io/robipozzi/windfire-restaurants-ui:1.0
          name: windfire-restaurants-ui
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - windfire-restaurants-ui
        from:
          kind: ImageStreamTag
          name: windfire-restaurants-ui:1.0
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: windfire-restaurants-ui
    name: windfire-restaurants-ui
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: windfire-restaurants-ui
      deploymentconfig: windfire-restaurants-ui
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: windfire-restaurants-ui
    name: windfire-restaurants-ui
  spec:
    host: windfire-restaurants-ui-windfire.robipozzi-rhocp-588309-3c76f4d12b7fe02f9cab56e64bec3e29-0000.eu-de.containers.appdomain.cloud
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: windfire-restaurants-ui
      weight: 100
    wildcardPolicy: None