--- # Ansible Playbook to automate application deployment to AWS in a consistent and repeatable way
- hosts: frontend
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    angular_dist_dir: "{{ lookup('env', 'PWD') }}/dist/windfire-restaurants-ui"
  vars_files:
    - "{{ src_dir }}/conf/aws-config.yml"
    - "{{ src_dir }}/conf/httpd.yml"
  tasks:
    - name: Transfer Angular Files
      copy:
        src: "{{ angular_dist_dir }}"
        dest: "{{ remote_app_home_dir }}"
    - name: Rename config-aws.json to config.json
      command: mv {{ remote_app_home_dir }}/{{ remote_app_files_dir }}/assets/config/config-aws.json {{ remote_app_home_dir }}/{{ remote_app_files_dir }}/assets/config/config.json
    - name: Clean Httpd folder {{ httpd_doc_dir }}
      file:
        path: "{{ httpd_doc_dir }}/"
        state: absent
    - name: Copy Angular application files from {{ remote_app_home_dir }}/{{ remote_app_files_dir }} to Httpd folder {{ httpd_doc_dir }}
      shell: 'cp -r {{ remote_app_home_dir }}/{{ remote_app_files_dir }} {{ httpd_doc_dir }}'
    - name: Clean folder {{ remote_app_home_dir }}/{{ remote_app_files_dir }}
      file:
        path: "{{ remote_app_home_dir }}/{{ remote_app_files_dir }}/"
        state: absent